version: '3.4'

services:
  catalogdb:
   image: postgres

volumes:
  postgres_catalog:



# services:
#   catalog.api:
#     image: ${DOCKER_REGISTRY-}catalogapi
#     build:
#       context: .
#       dockerfile: Catalog.API/Dockerfile
